import type { IndustryTemplate } from '../../types';

/**
 * 行业模板数据
 * 包含常见业态的标准分类、常用商品和存储位置
 */
export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
    {
        id: 'chinese-restaurant',
        name: 'Chinese Restaurant',
        nameZh: '中餐馆',
        description: '适合传统中餐馆的标准配置',
        icon: '🍜',
        categories: [
            { name: '主料' },
            { name: '肉类', parent: '主料' },
            { name: '海鲜', parent: '主料' },
            { name: '蔬菜', parent: '主料' },
            { name: '豆制品', parent: '主料' },
            { name: '调料' },
            { name: '酱料', parent: '调料' },
            { name: '干货', parent: '调料' },
            { name: '油脂', parent: '调料' },
            { name: '饮料' },
            { name: '酒水', parent: '饮料' },
            { name: '软饮', parent: '饮料' },
            { name: '米面粮油' },
            { name: '耗材' },
        ],
        items: [
            { name: '五花肉', category: '肉类', unit: 'kg', suggestedPar: 10 },
            { name: '猪里脊', category: '肉类', unit: 'kg', suggestedPar: 5 },
            { name: '鸡胸肉', category: '肉类', unit: 'kg', suggestedPar: 8 },
            { name: '牛腩', category: '肉类', unit: 'kg', suggestedPar: 5 },
            { name: '基围虾', category: '海鲜', unit: 'kg', suggestedPar: 3 },
            { name: '鲈鱼', category: '海鲜', unit: 'pcs', suggestedPar: 5 },
            { name: '白菜', category: '蔬菜', unit: 'kg', suggestedPar: 10 },
            { name: '青菜', category: '蔬菜', unit: 'kg', suggestedPar: 8 },
            { name: '土豆', category: '蔬菜', unit: 'kg', suggestedPar: 10 },
            { name: '番茄', category: '蔬菜', unit: 'kg', suggestedPar: 5 },
            { name: '豆腐', category: '豆制品', unit: 'pcs', suggestedPar: 20 },
            { name: '生抽', category: '酱料', unit: 'L', suggestedPar: 5 },
            { name: '老抽', category: '酱料', unit: 'L', suggestedPar: 3 },
            { name: '蚝油', category: '酱料', unit: 'L', suggestedPar: 2 },
            { name: '料酒', category: '酱料', unit: 'L', suggestedPar: 3 },
            { name: '食用油', category: '油脂', unit: 'L', suggestedPar: 20 },
            { name: '大米', category: '米面粮油', unit: 'kg', suggestedPar: 50 },
            { name: '面粉', category: '米面粮油', unit: 'kg', suggestedPar: 20 },
        ],
        locations: [
            { name: '后厨', type: 'Dry' },
            { name: '冷藏柜', type: 'Fridge' },
            { name: '冷冻库', type: 'Freezer' },
            { name: '干货区', type: 'Dry' },
            { name: '前厅吧台', type: 'Dry' },
        ],
    },
    {
        id: 'cafe',
        name: 'Cafe / Tea House',
        nameZh: '咖啡馆/茶饮店',
        description: '适合咖啡馆、奶茶店的标准配置',
        icon: '☕',
        categories: [
            { name: '咖啡豆' },
            { name: '茶叶' },
            { name: '乳制品' },
            { name: '糖浆' },
            { name: '小食原料' },
            { name: '包装材料' },
            { name: '调料' },
        ],
        items: [
            { name: '意式拼配豆', category: '咖啡豆', unit: 'kg', suggestedPar: 5 },
            { name: '单品豆', category: '咖啡豆', unit: 'kg', suggestedPar: 2 },
            { name: '红茶', category: '茶叶', unit: 'kg', suggestedPar: 2 },
            { name: '绿茶', category: '茶叶', unit: 'kg', suggestedPar: 2 },
            { name: '乌龙茶', category: '茶叶', unit: 'kg', suggestedPar: 1 },
            { name: '鲜牛奶', category: '乳制品', unit: 'L', suggestedPar: 20 },
            { name: '淡奶油', category: '乳制品', unit: 'L', suggestedPar: 5 },
            { name: '燕麦奶', category: '乳制品', unit: 'L', suggestedPar: 10 },
            { name: '香草糖浆', category: '糖浆', unit: 'L', suggestedPar: 2 },
            { name: '焦糖糖浆', category: '糖浆', unit: 'L', suggestedPar: 2 },
            { name: '榛果糖浆', category: '糖浆', unit: 'L', suggestedPar: 1 },
            { name: '纸杯(中)', category: '包装材料', unit: 'pcs', suggestedPar: 500 },
            { name: '纸杯(大)', category: '包装材料', unit: 'pcs', suggestedPar: 500 },
            { name: '杯盖', category: '包装材料', unit: 'pcs', suggestedPar: 1000 },
        ],
        locations: [
            { name: '吧台', type: 'Dry' },
            { name: '冷藏展示柜', type: 'Fridge' },
            { name: '储物间', type: 'Dry' },
            { name: '冷冻柜', type: 'Freezer' },
        ],
    },
    {
        id: 'bakery',
        name: 'Bakery',
        nameZh: '烘焙坊',
        description: '适合面包店、蛋糕店的标准配置',
        icon: '🥐',
        categories: [
            { name: '面粉类' },
            { name: '糖类' },
            { name: '乳制品' },
            { name: '油脂' },
            { name: '调味料' },
            { name: '水果' },
            { name: '巧克力' },
            { name: '包装' },
        ],
        items: [
            { name: '高筋面粉', category: '面粉类', unit: 'kg', suggestedPar: 50 },
            { name: '低筋面粉', category: '面粉类', unit: 'kg', suggestedPar: 30 },
            { name: '全麦粉', category: '面粉类', unit: 'kg', suggestedPar: 10 },
            { name: '白砂糖', category: '糖类', unit: 'kg', suggestedPar: 20 },
            { name: '糖粉', category: '糖类', unit: 'kg', suggestedPar: 5 },
            { name: '黄油', category: '乳制品', unit: 'kg', suggestedPar: 10 },
            { name: '淡奶油', category: '乳制品', unit: 'L', suggestedPar: 10 },
            { name: '鸡蛋', category: '乳制品', unit: 'pcs', suggestedPar: 200 },
            { name: '酵母', category: '调味料', unit: 'kg', suggestedPar: 2 },
            { name: '香草精', category: '调味料', unit: 'ml', suggestedPar: 500 },
            { name: '黑巧克力', category: '巧克力', unit: 'kg', suggestedPar: 5 },
            { name: '草莓', category: '水果', unit: 'kg', suggestedPar: 3 },
        ],
        locations: [
            { name: '烘焙间', type: 'Dry' },
            { name: '冷藏柜', type: 'Fridge' },
            { name: '冷冻库', type: 'Freezer' },
            { name: '展示柜', type: 'Fridge' },
            { name: '储物间', type: 'Dry' },
        ],
    },
    {
        id: 'convenience-store',
        name: 'Convenience Store',
        nameZh: '便利店',
        description: '适合便利店、小超市的标准配置',
        icon: '🏪',
        categories: [
            { name: '饮料' },
            { name: '零食' },
            { name: '速食' },
            { name: '日用品' },
            { name: '鲜食' },
            { name: '烟酒' },
        ],
        items: [
            { name: '矿泉水', category: '饮料', unit: 'pcs', suggestedPar: 100 },
            { name: '可乐', category: '饮料', unit: 'pcs', suggestedPar: 50 },
            { name: '薯片', category: '零食', unit: 'pcs', suggestedPar: 30 },
            { name: '方便面', category: '速食', unit: 'pcs', suggestedPar: 50 },
            { name: '关东煮', category: '鲜食', unit: 'pcs', suggestedPar: 20 },
            { name: '饭团', category: '鲜食', unit: 'pcs', suggestedPar: 15 },
            { name: '三明治', category: '鲜食', unit: 'pcs', suggestedPar: 10 },
        ],
        locations: [
            { name: '货架', type: 'Dry' },
            { name: '冷藏展柜', type: 'Fridge' },
            { name: '冷冻柜', type: 'Freezer' },
            { name: '收银台', type: 'Dry' },
            { name: '仓库', type: 'Dry' },
        ],
    },
    {
        id: 'hotpot',
        name: 'Hotpot Restaurant',
        nameZh: '火锅店',
        description: '适合火锅店的标准配置',
        icon: '🍲',
        categories: [
            { name: '肉类' },
            { name: '海鲜' },
            { name: '蔬菜' },
            { name: '丸滑类' },
            { name: '豆制品' },
            { name: '锅底' },
            { name: '调料' },
            { name: '饮料' },
        ],
        items: [
            { name: '肥牛卷', category: '肉类', unit: 'kg', suggestedPar: 20 },
            { name: '羊肉卷', category: '肉类', unit: 'kg', suggestedPar: 15 },
            { name: '毛肚', category: '肉类', unit: 'kg', suggestedPar: 10 },
            { name: '鸭血', category: '肉类', unit: 'kg', suggestedPar: 8 },
            { name: '虾滑', category: '丸滑类', unit: 'kg', suggestedPar: 5 },
            { name: '鱼丸', category: '丸滑类', unit: 'kg', suggestedPar: 5 },
            { name: '牛肉丸', category: '丸滑类', unit: 'kg', suggestedPar: 5 },
            { name: '娃娃菜', category: '蔬菜', unit: 'kg', suggestedPar: 15 },
            { name: '土豆片', category: '蔬菜', unit: 'kg', suggestedPar: 10 },
            { name: '藕片', category: '蔬菜', unit: 'kg', suggestedPar: 8 },
            { name: '豆腐', category: '豆制品', unit: 'pcs', suggestedPar: 30 },
            { name: '牛油锅底', category: '锅底', unit: 'pcs', suggestedPar: 20 },
            { name: '番茄锅底', category: '锅底', unit: 'pcs', suggestedPar: 15 },
            { name: '麻酱', category: '调料', unit: 'kg', suggestedPar: 5 },
        ],
        locations: [
            { name: '冷冻库', type: 'Freezer' },
            { name: '冷藏区', type: 'Fridge' },
            { name: '后厨', type: 'Dry' },
            { name: '调料台', type: 'Dry' },
        ],
    },
];

/**
 * 根据 ID 获取模板
 */
export const getTemplateById = (id: string): IndustryTemplate | undefined => {
    return INDUSTRY_TEMPLATES.find(t => t.id === id);
};
